
#  <auto-generated>
#    This code was generated by a tool.
#    Changes to this file may cause incorrect behavior and will be lost if
#    the code is regenerated.
#  </auto-generated>

@tool
class_name Schema
extends RefCounted

## 索敌类型
enum CardSelectType
{
    ## 自身
    SELF = 1,
    ## 单体敌人
    SINGLE_ENEMEY = 2,
    ## 所有敌人
    ALL_ENEMY = 3,
    ## 所有单位
    EVERYONE = 4,
}


## 卡牌类型
enum CardType
{
    ## 攻击卡
    ATTACK = 1,
    ## 技能卡
    SKILL = 2,
    ## 能量卡
    POWER = 3,
}


class CardEffectData:
    ## 造成伤害
    var damage: int
    ## 造成治疗
    var heal: int
    ## 施加防御
    var add_defend: int

    func _init(_json_) -> void:
        self.damage = _json_["damage"]
        self.heal = _json_["heal"]
        self.add_defend = _json_["add_defend"]





class CfgTables:
    ## 表单管理类 单例
    const json_path:String = "res://data/json/"

    static var instance : CfgTables

    func loader(file_name:String):
        var json_file = FileAccess.open(json_path + file_name + ".json", FileAccess.READ)
        var json_text = json_file.get_as_text()
        json_file.close()
        return JSON.parse_string(json_text)


    func _init() -> void:
        assert(instance == null,"gen:不要重复初始化CfgTables")


